---
format: html
editor: source
---

```{r}
#| include: false
library(vegan)
library(ggplot2)
library(ggpubr)
library(ggrepel)
library(ggdist)
library(scatterpie)
library(stringr)
library(RColorBrewer)
library(lmerTest)
library(multcomp)
library(fgsea)
library(hrbrthemes)
library(dplyr)
library(readr)
library(ggdist)
library(effectsize)
library(reshape2)
library(clusterProfiler)
library(GseaVis)
library(qqtest)
library(Maaslin2)
library(phyloseq)
library(zCompositions)

library(tidyverse)
library(tidymodels)
library(themis)
library(pROC)
library(recipeselectors)

library(DT)
library(downloadthis)
```

```{r}
#| include: false
meta_data <- read.csv("data/meta_data.tsv", sep = "\t")
meta_data$cancer_type[meta_data$cancer_type != "Melanoma"] <- "Other"

meta_data_2 <- read.csv("data/meta_data-v2.tsv", sep = "\t")
```

```{r}
#| include: false
ogu_table <- read.csv("data/ogu_table.tsv", sep = "\t")
```

```{r}
#| include: false
taxonomy <- read.csv("data/taxonomy.tsv", sep = "\t", row.names = 1)

kingdom <- sapply(str_split(taxonomy$Taxon, ";"), function(x) x[1])
phylum <- sapply(str_split(taxonomy$Taxon, ";"), function(x) x[2])
class_t <- sapply(str_split(taxonomy$Taxon, ";"), function(x) x[3])
order_t <- sapply(str_split(taxonomy$Taxon, ";"), function(x) x[4])
family_t <- sapply(str_split(taxonomy$Taxon, ";"), function(x) x[5])

genus <- sapply(str_split(taxonomy$Taxon, ";"), function(x) x[6])
genus[genus == "g__"] <- paste0(family_t[which(genus == "g__")], "_unknown")

species <- sapply(str_split(taxonomy$Taxon, ";"), function(x) x[7])

kingdom <- sub("d__", "", kingdom)
phylum <- sub("p__", "", phylum)
class_t <- sub("c__", "", class_t)
order_t <- sub("o__", "", order_t)
family_t <- sub("f__", "", family_t)
genus <- sub("g__", "", genus)
species <- sub("s__", "", species)

species <- gsub(paste(paste0("_", LETTERS), collapse = "|"), "", species)
genus <- gsub(paste(paste0("_", LETTERS), collapse = "|"), "", genus)

tax_table <- data.frame(kingdom, phylum, class = class_t, order = order_t, family = family_t, genus, species)
rownames(tax_table) <- rownames(taxonomy)

tax_table$phylum <- sapply(str_split(tax_table$phylum, "_"), function(x) x[1])
tax_table <- tax_table[rownames(tax_table) %in% colnames(ogu_table),]
```

```{r}
#| include: false
statistic <- read.csv("data/statistic.tsv", sep = "\t")
```

```{r}
#| include: false
ogu_table_t <- as.data.frame(t(ogu_table))
ogu_table_t <- cbind(featureid = rownames(ogu_table_t), ogu_table_t)
ogu_table_t <- merge(cbind(featureid = rownames(tax_table), tax_table), ogu_table_t, by = 1)
ogu_table_t <- ogu_table_t[-1]
```

```{r}
#| include: false
ogu.markers <- read.csv("data/ogu.biomarkers.tsv", sep = "\t")
ogu.markers <- merge(ogu.markers[c(2,1,3:6)], cbind(rownames(tax_table), tax_table), by = 1)

ogu.markers.2 <- read.csv("data/mags_biomarkers_melanoma_only.tsv", sep = "\t")
ogu.markers.2 <- merge(ogu.markers.2[c(2,1,3:4)], cbind(rownames(tax_table), tax_table), by = 1)

ogu.markers.3 <- read.csv("data/mags_biomarkers_non_melanoma.tsv", sep = "\t")
ogu.markers.3 <- merge(ogu.markers.3[c(2,1,3:4)], cbind(rownames(tax_table), tax_table), by = 1)
```

```{r}
#| include: false
songbird_Frankel_2017 <- read.csv("data/songbird/Frankel_2017/differentials.tsv", sep = "\t")
songbird_Gopalakrishnan_2019 <- read.csv("data/songbird/Gopalakrishnan_2019/differentials.tsv", sep = "\t")
songbird_Matson_2019 <- read.csv("data/songbird/Matson_2019/differentials.tsv", sep = "\t")

songbird_Spencer_2021 <- read.csv("data/songbird/Spencer_2021/differentials.tsv", sep = "\t")
songbird_Lee_2022 <- read.csv("data/songbird/Lee_2022/differentials.tsv", sep = "\t")

songbird_Liu_2022 <- read.csv("data/songbird/Liu_2022/differentials.tsv", sep = "\t")
songbird_McCulloch_2022 <- read.csv("data/songbird/McCulloch_2022/differentials.tsv", sep = "\t")
songbird_Peng_2020 <- read.csv("data/songbird/Peng_2020/differentials.tsv", sep = "\t")
songbird_Tsakmaklis_2023 <- read.csv("data/songbird/Tsakmaklis_2023/differentials.tsv", sep = "\t")
songbird_Gunjur_2024 <- read.csv("data/songbird/Gunjur_2024/differentials.tsv", sep = "\t")
songbird_Heshiki_2020 <- read.csv("data/songbird/Heshiki_2020/differentials.tsv", sep = "\t")
```

```{r}
#| include: false
songbird_coef <- rbind(songbird_Frankel_2017, songbird_Gopalakrishnan_2019, songbird_Matson_2019,
      songbird_Spencer_2021, songbird_Lee_2022, songbird_Liu_2022, songbird_McCulloch_2022,
      songbird_Peng_2020, songbird_Tsakmaklis_2023, songbird_Gunjur_2024, songbird_Heshiki_2020)

songbird_coef <- songbird_coef %>% group_by(featureid) %>% summarise(mean = mean(response.T.R.), sd = sd(response.T.R.))
songbird_coef <- as.data.frame(songbird_coef)

ogu.markers <- merge(ogu.markers, songbird_coef, by = 1)
ogu.markers <- ogu.markers[order(ogu.markers$num_datasets, decreasing = T),]
rownames(ogu.markers) <- 1:nrow(ogu.markers)
```

```{r}
#| include: false
songbird_coef_2 <- rbind(songbird_Frankel_2017, songbird_Gopalakrishnan_2019, songbird_Lee_2022, songbird_Matson_2019,
                         songbird_McCulloch_2022, songbird_Spencer_2021, songbird_Tsakmaklis_2023)

songbird_coef_2 <- songbird_coef_2 %>% group_by(featureid) %>% summarise(mean = mean(response.T.R.), sd = sd(response.T.R.))
songbird_coef_2 <- as.data.frame(songbird_coef_2)

ogu.markers.2 <- merge(ogu.markers.2, songbird_coef_2, by = 1)
ogu.markers.2 <- ogu.markers.2[order(ogu.markers.2$num_datasets, decreasing = T),]
rownames(ogu.markers.2) <- 1:nrow(ogu.markers.2)
```

```{r}
#| include: false
songbird_coef_3 <- rbind(songbird_Gunjur_2024, songbird_Heshiki_2020, songbird_Liu_2022, songbird_Peng_2020)

songbird_coef_3 <- songbird_coef_3 %>% group_by(featureid) %>% summarise(mean = mean(response.T.R.), sd = sd(response.T.R.))
songbird_coef_3 <- as.data.frame(songbird_coef_3)

ogu.markers.3 <- merge(ogu.markers.3, songbird_coef_3, by = 1)
ogu.markers.3 <- ogu.markers.3[order(ogu.markers.3$num_datasets, decreasing = T),]
rownames(ogu.markers.3) <- 1:nrow(ogu.markers.3)
```

```{r}
#| include: false
body_site <- read.csv("data/body_ogu.tsv", sep = "\t")[-2]
colnames(body_site)[2] <- "site"
body_site$genome <- sub(".fa", "", body_site$genome)

food <- read.csv("data/food_ogu.txt", sep = "\t", header = F)
colnames(food) <- "genome"
food$site <- "food"
food$genome <- sub(".fa", "", food$genome)

pathogens <- read.csv("data/pathogens_clusters.tsv", sep = "\t", header = T)
```

# Data overview

[MultiQC report](data/multiqc_report.html)

```{r}
#| echo: false
#| message: false
#| warning: false
datatable(meta_data, 
          caption = "Table 1. Sample metadata.",
          style = "bootstrap5", 
          extensions = 'Buttons', 
          options = list(dom = 'lBfrtip',
                         buttons = c('csv', 'excel')))
```

```{r}
#| echo: false
#| message: false
#| warning: false

colnames(statistic) <- c("sampleid", "dataset", "raw (mln)", "filtered (mln)", "% filtered")

datatable(statistic, 
          caption = "Table 2. Quality control statistics.",
          style = "bootstrap5", 
          extensions = 'Buttons', 
          options = list(dom = 'lBfrtip',
                         buttons = c('csv', 'excel')))
```

```{r}
#| include: false
#| warning: false
loc <- read_tsv('data/sum_location.tsv')

loc <- loc %>% 
  mutate(`sample number` = R + NR) %>% 
  mutate(nud_lat = case_when(              # nudging latitude to avoid overlaps
    dataset == 'Spencer_2021' ~ lat + 30,
    dataset == 'Matson_2019' ~ lat + 15,
    #dataset == 'Frankel_2017' ~ lat - 10,
    dataset == 'Gopalakrishnan_2018' ~ lat - 15,
    lat_lon == '51.49766788 N -0.119759159 W' ~ lat - 15,
    lat_lon == '53.80605739 N -1.522751916 W' ~ lat + 15,
    lat_lon == '53.22142806 N 6.574345097 E' ~ lat + 10,
    .default = lat)) %>% 
  mutate(nud_lon = case_when(              # nudging longititude to avoid overlaps
    dataset == 'Spencer_2021' ~ lon - 30,
    dataset == 'Matson_2019' ~ lon + 5,
    #dataset == 'Frankel_2017' ~ lon - 15,
    dataset == 'Gopalakrishnan_2018' ~ lon + 5,
    lat_lon == '51.49766788 N -0.119759159 W' ~ lon - 25,
    lat_lon == '53.42969912 N -2.228100629 W' ~ lon - 15,
    lat_lon == '53.80605739 N -1.522751916 W' ~ lon + 5,
    lat_lon == '53.22142806 N 6.574345097 E' ~ lon + 20,
    .default = lon))
```

```{r}
#| label: dvsdfv
#| include: false
sample_map <- ggplot(data = loc) +
    borders("world", colour = "gray58", fill = "gray") +
    # coord_cartesian(xlim = c(-180, 180), ylim = c(-55, 85)) +
    geom_point(aes(x = nud_lon, y = nud_lat, size = `sample number`), shape = 1) +
    scale_radius(range = c(7, 18)) +
  geom_scatterpie(
      aes(x = nud_lon, y = nud_lat, group = dataset, r = sqrt(`sample number`)),
      cols = c("R", "NR"),
      color = 'black') +
  scale_fill_manual(values = c("R" = "#377EB8", "NR" = "#E41A1C")) +
  geom_segment(aes(x = nud_lon, y = nud_lat, xend = lon, yend = lat), 
               color = 'gray25', linewidth = 0.7) +
  geom_label_repel(aes(x = nud_lon, y = nud_lat, label = dataset),
    size = 4, direction = "both", segment.color = 'black',
    force = 4, min.segment.length = 0.5, nudge_x = -2) +
  labs(x = "Longitude", y = "Latitude") +
  theme_bw()+
    theme(
        axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank()) + 
    theme(
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.border = element_rect(fill = NA))
```

[Figure 1](data/sample_map.pdf)
```{r fig.width=15, fig.height=6}
#| echo: false
#| message: false
#| warning: false
#| fig-cap: Figure 1. Global distribution of collected samples (n=624) across countries. Circle size represents sample count per region, while color indicates the proportion of patients R - responsive (or NR - non-responsive) to immunotherapy.
sample_map
```

# MAG assembled statistics

# Taxonomy table
```{r}
#| echo: false
#| message: false
#| warning: false
datatable(ogu_table_t, 
          caption = "Table 3. Operational genomic unit (OGU) abundance profile by samples.",
          style = "bootstrap5", 
          extensions = 'Buttons', 
          options = list(dom = 'lBfrtip',
                         buttons = c('csv', 'excel')))
```

# Marker OGUs discovery
## All
```{r}
#| echo: false
#| message: false
#| warning: false
datatable(ogu.markers, 
          caption = "Table 4. All marker OGU with Sondbird coefficients (MEAN ± SD).",
          style = "bootstrap5", 
          extensions = 'Buttons', 
          options = list(dom = 'lBfrtip',
                         buttons = c('csv', 'excel')))
```

```{r}
#| include: false
coef_barplot <- ggplot(songbird_coef, aes(x = reorder(featureid, mean), y=mean)) + 
    geom_errorbar(aes(ymin=mean-sd, ymax=mean+sd), width=.2,
        position=position_dodge(0.05), col = "gray58") +
    # geom_point(shape = 0, size = 0.25)+
    geom_hline(yintercept = 0, col = "red")+
    theme_bw()+
    theme(
        axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank()) + 
    theme(
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.border = element_rect(fill = NA))+
    ylab("Mean R/NR + k")+
    xlab("OGUs")
```

```{r fig.width=8, fig.height=3}
#| echo: false
download_this(
  coef_barplot,
  output_name = "coef_barplot",
  output_extension = ".pdf",
  button_label = "PDF",
  button_type = "primary"
)
```

```{r fig.width=8, fig.height=3}
#| echo: false
#| fig-cap: Figure 2. The barplot depicts Songbird differential abundance coefficients (MEAN ± SD) for marker Operational Genomic Units (OGUs), with the x-axis representing individual OGUs and the y-axis showing the magnitude and direction of association coefficients - All.
coef_barplot
```

```{r}
#| include: false
ogu_table.markers <- ogu_table[colnames(ogu_table) %in% ogu.markers.sbs$featureid]
ogu_table.markers <- ogu_table.markers + 0.0001

df.log_ratio <- NULL
for (i in rownames(ogu_table.markers)){
    df <- ogu_table.markers[rownames(ogu_table.markers) %in% i,]
    
    df_denominator <- df[colnames(df) %in% ogu.markers$featureid[ogu.markers$biomarker == "denominator"]]
    df_numerator <- df[colnames(df) %in% ogu.markers$featureid[ogu.markers$biomarker == "numerator"]]
    
    df_denominator <- df_denominator[df_denominator > 0]
    df_numerator <- df_numerator[df_numerator > 0]
    
    log_ratio <- log(sum(df_numerator)/sum(df_denominator))
    df.s <- data.frame(sampleid = i, log_ratio)
    df.log_ratio <- rbind(df.s, df.log_ratio)
}

df.log_ratio <- merge(meta_data, df.log_ratio, by = 1)
```

```{r}
#| echo: false
#| message: false
#| warning: false
datatable(df.log_ratio, 
          caption = "Table 5. Log ratio (LR) values of marker OGU across samples - All cancers.",
          style = "bootstrap5", 
          extensions = 'Buttons', 
          options = list(dom = 'lBfrtip',
                         buttons = c('csv', 'excel')))
```

```{r}
#| message: true
#| warning: false
#| include: false
logratio_plot <- ggplot(df.log_ratio, aes(log_ratio, response, col = response))+
      stat_halfeye()+
      xlab("Log ratio")+
      ylab("Response")+
      theme_pubr()+
      theme(legend.position = "none")+
      scale_color_brewer(palette = "Set1")
```

```{r fig.width=4, fig.height=3}
#| echo: false
download_this(
  logratio_plot,
  output_name = "logratio_plot",
  output_extension = ".pdf",
  button_label = "PDF",
  button_type = "primary"
)
```

```{r fig.width=4, fig.height=3}
#| echo: false
#| fig-cap: Figure 3. The boxplot shows log ratio (LR) values obtained using marker OGU. LR is highest in the R group (median = 3.0) and lowest in NR group (median = 1.4).
logratio_plot
```

```{r}
#| echo: false
lmer.log_ratio <- lmer(log_ratio ~ response + (1|dataset), data = df.log_ratio)
```

##### lmer test results
```{r}
#| echo: false
summary(glht(lmer.log_ratio, linfct = mcp(response = "Tukey")), test = adjusted("bonferroni"))
```

##### Dataset variable inportance
```{r}
#| echo: false
ranova(lmer.log_ratio)
```

##### Residuals of the model normality testing
[Figure 4](data/qqplot.pdf)

```{r fig.width=5, fig.height=4}
#| echo: false
#| fig-cap: Figure 4. Quantile-quantile diagram of mixed linear model residuals.
shapiro.test(residuals(lmer.log_ratio))
qplot(residuals(lmer.log_ratio), dist = "normal")
```

##### Effect size estimation
```{r}
#| echo: false
cohens_d(log_ratio ~ response, data = df.log_ratio)
```

## Melanoma
```{r}
#| echo: false
#| message: false
#| warning: false
datatable(ogu.markers.2, 
          caption = "Table 6. Melanoma marker OGU with Sondbird coefficients (MEAN ± SD).",
          style = "bootstrap5", 
          extensions = 'Buttons', 
          options = list(dom = 'lBfrtip',
                         buttons = c('csv', 'excel')))
```

```{r}
#| include: false
coef_barplot_2 <- ggplot(songbird_coef_2, aes(x = reorder(featureid, mean), y=mean)) + 
    geom_errorbar(aes(ymin=mean-sd, ymax=mean+sd), width=.2,
        position=position_dodge(0.05), col = "gray58") +
    # geom_point(shape = 0, size = 0.25)+
    geom_hline(yintercept = 0, col = "red")+
    theme_bw()+
    theme(
        axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank()) + 
    theme(
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.border = element_rect(fill = NA))+
    ylab("Mean R/NR + k")+
    xlab("OGUs")
```

```{r fig.width=8, fig.height=3}
#| echo: false
download_this(
  coef_barplot_2,
  output_name = "coef_barplot_2",
  output_extension = ".pdf",
  button_label = "PDF",
  button_type = "primary"
)
```

```{r fig.width=8, fig.height=3}
#| echo: false
#| fig-cap: Figure 4. The barplot depicts Songbird differential abundance coefficients (MEAN ± SD) for marker Operational Genomic Units (OGUs), with the x-axis representing individual OGUs and the y-axis showing the magnitude and direction of association coefficients - Melanoma.
coef_barplot_2
```

## Other cancers
```{r}
#| echo: false
#| message: false
#| warning: false
datatable(ogu.markers.3, 
          caption = "Table 7. Melanoma marker OGU with Sondbird coefficients (MEAN ± SD).",
          style = "bootstrap5", 
          extensions = 'Buttons', 
          options = list(dom = 'lBfrtip',
                         buttons = c('csv', 'excel')))
```

```{r}
#| include: false
coef_barplot_3 <- ggplot(songbird_coef_3, aes(x = reorder(featureid, mean), y=mean)) + 
    geom_errorbar(aes(ymin=mean-sd, ymax=mean+sd), width=.2,
        position=position_dodge(0.05), col = "gray58") +
    # geom_point(shape = 0, size = 0.25)+
    geom_hline(yintercept = 0, col = "red")+
    theme_bw()+
    theme(
        axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank()) + 
    theme(
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.border = element_rect(fill = NA))+
    ylab("Mean R/NR + k")+
    xlab("OGUs")
```

```{r fig.width=8, fig.height=3}
#| echo: false
download_this(
  coef_barplot_3,
  output_name = "coef_barplot_3",
  output_extension = ".pdf",
  button_label = "PDF",
  button_type = "primary"
)
```

```{r fig.width=8, fig.height=3}
#| echo: false
#| fig-cap: Figure 6. The barplot depicts Songbird differential abundance coefficients (MEAN ± SD) for marker Operational Genomic Units (OGUs), with the x-axis representing individual OGUs and the y-axis showing the magnitude and direction of association coefficients - Other cancer types.
coef_barplot_3
```

```{r}
ogu.markers.sbs  <- ogu.markers[ogu.markers$num_d_other > 0,]

sort(table(ogu.markers.sbs$species[ogu.markers.sbs$biomarker == "numerator"]))

vec11 <- ogu.markers.sbs$mean
names(vec11) <- ogu.markers.sbs$featureid
vec11 <- sort(vec11, decreasing = T)

vec2 <- ogu.markers.2$mean
names(vec2) <- ogu.markers.2$featureid
vec2 <- sort(vec2, decreasing = T)

vec3 <- ogu.markers.3$mean
names(vec3) <- ogu.markers.3$featureid
vec3 <- sort(vec3, decreasing = T)

gsea_genus_1 <- GSEA(vec1, TERM2GENE = ogu.markers[c(12,1)], eps = 0, pAdjustMethod = "BH")
gsea_genus_11 <- GSEA(vec11, TERM2GENE = ogu.markers.sbs[c(12,1)], eps = 0, pAdjustMethod = "BH")

gsea_phylum_1 <- GSEA(vec1, TERM2GENE = ogu.markers[c(8,1)], eps = 0, pAdjustMethod = "BH")
gsea_phylum_11 <- GSEA(vec11, TERM2GENE = ogu.markers.sbs[c(8,1)], eps = 0, pAdjustMethod = "BH")

gsea_bodysite_2 <- GSEA(vec2, TERM2GENE = body_site[c(2,1)], pAdjustMethod = "BH")
gsea_bodysite_3 <- GSEA(vec3, TERM2GENE = body_site[c(2,1)], pAdjustMethod = "BH")
gsea_bodysite_11 <- GSEA(vec11, TERM2GENE = body_site[c(2,1)], pAdjustMethod = "BH")

gsea_food_2 <- GSEA(vec2, TERM2GENE = food[c(2,1)], pAdjustMethod = "BH")
gsea_food_3 <- GSEA(vec3, TERM2GENE = food[c(2,1)], pAdjustMethod = "BH")
gsea_food_11 <- GSEA(vec11, TERM2GENE = food[c(2,1)], pAdjustMethod = "BH")

gsea_pathogens_11 <- GSEA(vec2, TERM2GENE = pathogens[c(2,1)], pAdjustMethod = "BH")

gsea_genus_plot_1 <- gseaNb(object = gsea_genus_1, 
      geneSetID = gsea_genus_1$ID, 
      curveCol = brewer.pal(name = "Set1", n = 9), 
      htCol = c("#A50F15", "#08519C"))

gsea_genus_plot_11 <- gseaNb(object = gsea_genus_11, 
      geneSetID = gsea_genus_11$ID, 
      curveCol = brewer.pal(name = "Set1", n = 9), 
      htCol = c("#A50F15", "#08519C"))
```